dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
before_install:
  - sudo apt-get install python-dev libgmp3-dev
install:
  - pip install pycodestyle pytest pytest-cov
before_script:
  - pycodestyle --max-line-length=200 --ignore=E402,W605 */*.py
  - pip install -e .
script:
  - pytest --cov=fastecdsa
